layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"
route_cache: 0
template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_EXT: ".ttc" 
    COMPILE_DIR: "/tmp/ttcompile"

# broadway
broadway:
  title: "Perl Dancer"
  date: "Feb. 24, 2011"
  event: "BPW 2011"
  author: "Alexis Sukrieh"
  slides: 64
  refresh_rate: 600
  remote: 0

